# Generated by Django 2.1.5 on 2019-10-28 19:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='owner',
            field=models.ManyToManyField(limit_choices_to={'is_superuser': False}, related_name='profiles', to=settings.AUTH_USER_MODEL),
        ),
    ]
