# Generated by Django 2.1.5 on 2019-10-31 09:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logs',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 31, 9, 53, 19, 693815, tzinfo=utc)),
        ),
    ]
