# Generated by Django 2.1.5 on 2019-10-31 10:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20191031_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='MACAddress',
            field=models.TextField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='customuser',
            name='remoteLog',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='logs',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 31, 10, 3, 50, 954561, tzinfo=utc)),
        ),
    ]
