# Generated by Django 2.1.5 on 2019-10-31 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20191031_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='MACAddress',
            field=models.CharField(default='', max_length=100),
        ),
    ]
