# Generated by Django 2.1.5 on 2019-12-02 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20191031_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logs',
            name='data',
            field=models.TextField(blank=True, max_length=40000),
        ),
        migrations.AlterField(
            model_name='logs',
            name='notes',
            field=models.TextField(blank=True, max_length=40000),
        ),
    ]
