# Generated by Django 2.1.5 on 2020-03-10 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20200310_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
