# Generated by Django 2.1.5 on 2020-04-17 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20200415_1241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='configuration',
        ),
    ]
