# Generated by Django 2.1.5 on 2020-04-17 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_remove_device_configuration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='subscription_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.SubscriptionType'),
        ),
    ]
